### ISSUE TITLE
Expose name for UIImage

### ISSUE THREAD

**Issue by danishin** [mac-cain13/R.swift#134]
I find myself often in my tests converting `UIImage` to `NSData` to compare their bytes for equality.

It'd be nice to simply do string equality for all the images that are exposed through R.swift!

I found `name` is provided for `R.nib.*`. 

Could we add this? Perhaps we can make `R.imageName` or something similar if wrapping `R.image` with another `struct` is not preferable?
 
BTW, great library! No more stupid runtime errors :smile: :+1:

**Comment by mac-cain13** [comment]
Thanks for your input! I think this is somewhat related to #132. It would be nice to be able to get more info about an image.

We could refactor `R.image.myImage` from the `UIImage` that it is now, to a `ImageInfo` struct that could be something like this:

```
struct ImageInfo {
  let name: String
  let path: NSURL
  func instance() -> UIImage
}```

Pros:
- More advanced use of images is supported
- It's more in line with other resources like nibs
- We could create a `UIImage.init(imageInfo: ImageInfo)` constructor, which is closer to the standard libraries (which is one of the goals of R.swift)

Cons:
- `imgView.image = R.image.myImage` becomes `imgView.image = R.image.myImage.instance()` or imgView.image = UIImage(imageInfo: R.image.myImage)`
- It's a breaking change

I'm in doubt if the pro's outweight the cons. I would value views and options on this from users. Especially from you @danishin and from @kenyth and @tomlokhorst. Anyone cares to share their opinion?

**Comment by danishin** [comment]
Thanks for your response! 

Having a wrapper object for `UIImage` with type safety can be very useful not only for testing but also we can do lazy evaluation for returning `UIImage`. Instead of passing around memory hogging `UIImage` around by prematurely creating it, we can easily pass around this `ImageInfo` struct and only call `instance()` method when it is strictly needed.

I'm currently using MVVM pattern and this would be immensely useful not only for testing but also for performance reasons. Currently, my `ViewModel`s exposes `UIImage`, which causes the image to be created prematurely. Instead, vm can expose `ImageInfo` struct and `View` can call `instance()` when the view is actually loaded.

I'm sure there are many other beneficial use cases for both performance, clarity and testing by enabling advanced `UIImage` handling which is simply not possible with plain Cocoa (more than just a mere type safety)

**Comment by kenyth** [comment]
Thanks for referring to me.

At first thought, and following what's been done in ```_R.nib```, a struct containing more meta information is reasonable, and what we proposed in #132 could easily fit in.

But at a second thought, it depends. It depends on how far R.swift wants to go.

What's the design purpose, or responsibilities of R.swift? For me, it attracts me much in two aspects:
- it localizes and modularize/encapsulate what's inclined to change, which provides language level (not literal string level) reuse of code and also in this specific case compile-time check (it's much like its counterpart in Android development)
- it is nonintrusive, seamlessly fitting into the existing workflow before R.swift, so it provides a natural adoption path (and because of this, I mentioned the warning thing in #132)

Only with these two core benefits, I would intend to use R.swift. Let's say even if it's as simple as below:
- ```R.names.xx```, ```R.names.yy``` (or ```R.names.image.xx```, ...)
- the current nonintrusive workflow

What we're talking about is basically easy access of resource and/or its meta information. Without R.swift, it's all done by developers themselves, with literal strings. The two core benefits is a Yes or No question. But this is NOT a Yes or No question. Of course the user (developer) of R.swift, or any user of any product, could be greedy, they just want to have everything that's convenient for their development.

So as I said, it depends. But as a user of R.swift, I'd like to have R.swift at hand be as convenient as possible, **IF** the balance between complexity and efficiency is well kept, by saying which I mean if the conveniences bring too much complexity, maybe it belongs to another library than R.swift.

Just a thought, maybe it doesn't help.  Thanks.

**Comment by kenyth** [comment]
Or let's say, if without R.swift, what would @danishin do with his/her code? or what would I do in #132? Maybe R.swift should at first provide super succinctly easy access of resource, and then literal names of all resources (as mentioned above ```R.names.xx```, ```R.names.yy``` or ```R.names.image.xx```, ...), with which the user can do anything themselves.

So, looking forward, as R.swift evolves in the future, it doesn't need to include every way of access of resources and/or its meta information, just because the users say so, but just include the most popular/necessary ways. For any other ways, the users can temporarily or permanently do themselves by using ```R.names.xx```.

**Comment by mac-cain13** [comment]
Thanks for the input, I'm giving the `ImageInfo` struct a shot right now. :)

**Comment by mac-cain13** [comment]
Update:

I've made the first steps for this on the 1.0.0 branch. Images will change to the following syntax in R.swift 1.0:

```swift
// R.swift 1.0: Using UIImage(named:)
let image = R.image.settingsIcon()

// R.swift 1.1: Get image name
// Concept code, subject to change etc etc
let imageName = R.image.settingsIcon.name

// R.swift 1.1: Get lightweight image information struct to pass around or use in tests
// Concept code, subject to change etc etc
let imageInformation = R.image.settingsIcon
```

So I've made the first changes to support this, in the future more "meta" info will be available for resources so you can use it in a more flexible way. :)

**Comment by danishin** [comment]
Amazing work with the API. Will look forward to 1.1. I appreciate your work :smile:

**Comment by mac-cain13** [comment]
And this is in the 1.0 branch now. `ImageResourceType` is not yet equatable, if you have a nice use case for it feel free to open a PR or new issue. Isn't that hard to add, but the main point of this issue is resolved and I don't want to add too much to the 1.0 release without a very good reason. :)
