### ISSUE TITLE
R.generated.swift compile error

### ISSUE THREAD

**Issue by Bijiabo** [mac-cain13/R.swift#164]
After build my project, the `R.generated.swift` code has two error:

line 43:
```
  static let  = ImageResource(bundle: _R.hostingBundle, name: "@")
```

line 175:
```
static func (compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image., compatibleWithTraitCollection: traitCollection)
    }
```

use R.swift 1.3.0 and install manually in Xcode 7 .
What's wrong? How to deal with it ?

**Comment by mac-cain13** [comment]
Thanks for using R.swift and reporting you're issue!

Looks like you have an image named `@` in your project, is that correct? The name of this image is only a symbol, which is not a valid Swift identifier for a variable. So we can't generate something like `R.image.@` for you.

A workaround is to rename the image to something with alphanumeric characters, something like `at` or `atIcon` for example. That should work.

I'll look into it, because I think R.swift should generate a warning for this issue and skip the image. The generated code should always compile even with these kind of image names.

**Comment by mac-cain13** [comment]
Looks like we already have an issue for this problem: #137

I'll close this one, but feel free to ask and questions or add comments to this or the other issue!
