### ISSUE TITLE
Strange error: missing --bundleIdentifier

### ISSUE THREAD

**Issue by tomekc** [mac-cain13/R.swift#167]
I just upgraded from 0.10 to 1.3 and script that always worked:

`"$PODS_ROOT/R.swift/rswift" "$SRCROOT/BackOffice"`

fails with following error. I did not find anything in the docs about new command line parameters?

```
error: [R.swift] Missing option: --bundleIdentifier requires 1 parameters 
usage: rswift [-p|--xcodeproj] [-t|--target] [--bundleIdentifier]
              [--buildProductsDir] [--developerDir] [--sourceRoot] [--sdkRoot]
              [--productModuleName] [-h|--help]
```

Will be grateful for some hints on this.

**Comment by mac-cain13** [comment]
Since version 1.0 R.swift uses the bundle identifier of your project in the generated file, so that's why you see the error now. It should automatically detect this when you run R.swift from within a Xcode build.

Seems like your project doesn't expose the `PRODUCT_BUNDLE_IDENTIFIER` environment variable. Do you do anything special with the bundle identifier? Maybe you can take a look at the build log to see what variables are exposed when running R.swift and check if `PRODUCT_BUNDLE_IDENTIFIER` is indeed set to your bundle identifier.

**Comment by mac-cain13** [comment]
Btw, could be your issue is the same as this one: https://github.com/mac-cain13/R.swift/issues/116
Maybe checking that one out helps.

**Comment by mac-cain13** [comment]
@tomekc I assume your issue is solved. If not feel free to comment on this issue.

**Comment by hardeep68** [comment]
I'm facing same issue.

Actually, we are using .xcconfig files to handle multiple environments. When we replace $(PRODUCT_BUNDLE_IDENTIFIER)  with our .config file key $(APP_IDENTIFIER) then it is showing following error.  

error: [R.swift] Missing option: --bundleIdentifier requires 1 parameters 
usage: rswift [--version] [--edge] [--import] [--accessLevel] [--rswiftignore]
              [-p|--xcodeproj] [-t|--target] [--bundleIdentifier]
              [--buildProductsDir] [--developerDir] [--sourceRoot] [--sdkRoot]
              [--productModuleName] [-h|--help]
