### ISSUE TITLE
Add support for R.colors from .clr files

### ISSUE THREAD

**Issue by tomlokhorst** [mac-cain13/R.swift#169]
Mentioned by @renrawnalon in https://github.com/mac-cain13/R.swift/issues/41#issuecomment-187021929 R.swift could support generating colors from .clr files.

See also: https://www.natashatherobot.com/xcode-color-palette/

Although the exact workflow for adding a color pallete to R.colors isn't clear.
Since the Xcode project itself doesn't reference the .clr file.
And R.swift can't just use everything from `~/Library/Colors/*.clr`, because the R.generated.swift file would then be different for each member of a team.

Maybe the user should pass a directory of .clr files to the `rswift` executable from the Build Phase? That seems less than ideal.

**Comment by renrawnalon** [comment]
Thanks for creating this issue. I've also considered how colors with fit in with the R.swift ecosystem, and for the reason you mentioned where the Xcode project doesn't reference .clr files, it doesn't seem to fit in. This also relates to one problem that I'm having with using .clr files, which is that it's difficult to put the .clr file for a project under version control. There are a few reasons for this:

1. .clr files are binary files, so it's not possible to git to merge changes from multiple people. As far as I know, the only way to parse these binary files is with a mac app using the NSColorList class as described [here](http://stackoverflow.com/questions/11386513/how-to-create-osx-clr-palette-files).
2. When a change is made to a color palette via Xcode, the ~/Library/Colors/Project.clr file is completely overridden. This breaks any symlinks to the file, so that isn't a reasonable solution.

Our current solution is to keep a copy of the file checked into out project, then manually copy it to and from ~/Library/Colors when changes are made. Every time this is done, a restart of Xcode is required to refresh the color palette in IB. This is obviously not an ideal solution.

Since this problem is not really in the scope of the problem that R.swift attempts to solve, I don't know if R.colors should be included in the main R.swift library. Does the idea of creating a sub-library for R.color like "R.swift.color" that takes the path to a color.clr file for directory somewhere in a project as a parameter sound like overkill?

**Comment by tomlokhorst** [comment]
Thinking about this some more. I think most of the problems here are outside the scope of R.swift to solve.

One way to solve the "multiple people edit the same color palette"-problem; Use a tool that maps a .clr-file to a textual representation (two-way). That way, the text file can be checked in, and any conflicts can easily be resolved.
For the "installation in user directory"-problem; A build step could copy the .clr files from the repository to ~/Library/Colors and show a warning.

Not sure if these are the best solutions (probably not), but both are outside the scope of R.swift. The best thing R.swift can do is map from some Apple format (storyboard, xib, xcodeproj, clr) to a statically typed struct. All remaining problems can be solved by some other tool

In that vein, I've created [a pull request](https://github.com/mac-cain13/R.swift/issues/174) which adds support for parsing .clr color palette files.

**Comment by mac-cain13** [comment]
Merged in the PR, this will be in the next release.
