### ISSUE TITLE
R.swift.Library v1.2.1 should be v1.3.0

### ISSUE THREAD

**Issue by mdubs** [mac-cain13/R.swift#180]
As a result of the change in the library to use Swift 2.2 syntax.  It is not possible to stay update pods while staying on Swift 2.1 without specifying specific version of both R.swift and R.swift.Library.  This is because restricting R.swift to version 1.4.0 will still use R.swift.Library 1.2.1 since it uses the optimistic operator for version comparison so 1.2.1 satisfies the constraint '~> 1.2.0'.  Since this was a breaking change, the R.swift.Library should have become 1.3.0 and and potentially R.swift becomes 1.5.0.  The only way to fix this now would be either to republish what is 1.2.1 as 1.3.0 and remove the current 1.2.1 or publish what was 1.2.0 as 1.2.2 in addition to republishing 1.2.1 as 1.3.0

**Comment by tomlokhorst** [comment]
As a workaround:
You can specify the exact R.swift.Library version in the Podfile:

```
pod 'R.swift', '1.4.0'
pod 'R.swift.Library', '1.2.0'
```

So sorry about this! We'll work on fixing this by republishing as soon as possible.

**Comment by mac-cain13** [comment]
Mea culpa, I rushed the new version out without taking versioning into account well enough. No I think about it this even should be a major release, since it is a breaking change.

This is what I'm going to do to fix this:
- Release v1.4.2 that is compatible with Swift 2.1 (this will be exactly the same as 1.4.0)
- Release v2.0.0 that is the Swift 2.2 version (this will be exactly the same as 1.4.1)

I'm currently in the process of releasing those versions.
