### ISSUE TITLE
Add support for bundle folder

### ISSUE THREAD

**Issue by vladimirvrabel** [mac-cain13/R.swift#186]
Hi, 

please add support for items in Resources.bundle e.g.: Resources.bundle/images/myimage@2x.png. Because when we use Resources.bundle, then there are not changes at pbxproj file for each change in this directory with using git

Thanks

**Comment by mac-cain13** [comment]
I'm not sure how many people would benefit from supporting bundles, if you have a pure Swift project you can just use frameworks and generate a `R.generated.swift` file within the project exposing the resources in there. A seperate bundle with resources sounds to me like a thing from the ObjC world with static linked frameworks that couldn't include resources.

Maybe I'm wrong, love to hear about the use cases, but I don't think this is a top priority.

**Comment by martinflorek** [comment]
We use bundle folders for easy collaboration with designers. They behave like referenced folders in Xcode, no change to the .pbxproj file for easy GIT. No need to handle .xcassets JSON structure, no slow drag-&-drop of resources in Xcode, no problems with resources renaming and moving. Designers just export PNGs into the bundle and push to GIT repository. No need to learn designers anything about the Xcode and GIT conflicts resolving.

Bundles have too many pluses to not to use them.

**Comment by kristiyanP** [comment]
@martinflorek 
If your designers use sketch you may want to check these two plugins:
https://github.com/iGenius-Srl/Seca
https://github.com/iGenius-Srl/sketch-app-asset-export

**The resources exported with these plugins generate also the json structure ( for ios only) and take care of the naming conventions**

### What we do:
We have a git repo where designers export using these plugins
Then for both iOS and Android we have a python script that just copies the files in the project at build time.

**Comment by mac-cain13** [comment]
Together with @tomlokhorst I looked into bundle support. Also relates to CocoaPods w/bundles as discussed in #295.

We think R.swift should detect the bundle by itself, since bundles are also mentioned in the Copy Resources build phase in Xcode. So we can detect them automatically and then put all resources found in that bundle under `R.bundle.myBundle.*`.

This more robust than the proposed solution in PR #395 since this won't support having both resources in your project as well as in one or more bundles. Detecting bundles, picking out all resources and adding them in the R file should not be too hard to implement.

**Comment by cooler333** [comment]
What about static frameworks? It's not contain resources

**Comment by cooler333** [comment]
Static frameworks used for performance reason. We have about 200 pods in podfile.lock, and with dynamic frameworks app load about 15-30 sec dependent on iPhone model/iOS version. With static it takes about 3-5 sec.

**Comment by llOldmenll** [comment]
> Together with @tomlokhorst I looked into bundle support. Also relates to CocoaPods w/bundles as discussed in #295.
> 
> We think R.swift should detect the bundle by itself, since bundles are also mentioned in the Copy Resources build phase in Xcode. So we can detect them automatically and then put all resources found in that bundle under `R.bundle.myBundle.*`.
> 
> This more robust than the proposed solution in PR #395 since this won't support having both resources in your project as well as in one or more bundles. Detecting bundles, picking out all resources and adding them in the R file should not be too hard to implement.

Hi. Has it (`R.bundle.myBundle.*`) been already implemented?

**Comment by rakuyoMo** [comment]
Same question, how long will it take to implement this feature?

**Comment by tumata** [comment]
Seems this issue was opened in 2016. Was is the current status in 2022?

Our framework, because of dependencies, must be released as a static framework. I'm running into this issue now and wondering if I should remove `R.swift` entirely form our library of if I can fix it somehow.

Thanks for your help in providing an answer!

**Comment by tumata** [comment]
Seems this issue was opened in 2016. Was is the current status in 2022?

Our static framework must use the `resource_bundles` to add our resources. I saw a comment about support here: https://github.com/mac-cain13/R.swift/issues/295#issuecomment-617811400

Is this being considered for work or should I consider the workaround provided by https://github.com/mac-cain13/R.swift/issues/295#issuecomment-328984986 or removing R.swift entirely ?

**Comment by tomlokhorst** [comment]
Bundles are supported, see the example [RswiftAppWithStaticFrameworks](https://github.com/mac-cain13/R.swift/tree/master/Examples/RswiftAppWithStaticFrameworks)

**Comment by dong2dong3** [comment]
hi @tomlokhorst is cocoapods also supported?
