### ISSUE TITLE
R.swift support the Localizable.strings have problems.

### ISSUE THREAD

**Issue by arden** [mac-cain13/R.swift#199]
R.swift support the Localizable.strings have some problems.

when my Localizable.strings's str have a '\r\n', there have some problems as below.
Localizable.strings
"We need a couple things\r\nbefore you get started." = "We need a couple things\r\nbefore you get started."

```swift
static let weNeedACoupleThingsBeforeYouGetStarted = StringResource(key: "We need a couple things
\nbefore you get started.", tableName: "Localizable", locales: ["zh-Hans"])
```

**Comment by tomlokhorst** [comment]
Thanks for reporting this problem!
Apparently I forgot to check for CR+LF `\r\n`, only the LF `\n` was correctly escaped.

The fix for this is in https://github.com/mac-cain13/R.swift/issues/200.

---

As a side note:
With R.string there is less need for using localized string keys of this form.

Using something like `NSLocalizedString("Welcome to this app", comment: "")` in your code has two use cases: 
 1. These can be found by `genstrings` to generate a `Localizable.strings` file.
 2. When the key is not translated, NSLocalizedString will fall back to the key itself.

These use cases do not apply when using R.strings:

1. `genstrings` will no longer work, because all string references in your code are static references.
2. If a key is (no longer) in the `Localizable.strings` file, no value is generated, so this would lead to a compile time error.

Because of this, I usually replace keys like `"Welcome to this app"` with something like: `"welcome.message"`.

**Comment by mac-cain13** [comment]
I'll merge and release the fix from @tomlokhorst!
