### ISSUE TITLE
Not compatible with ECSlidingViewController

### ISSUE THREAD

**Issue by kaunteya** [mac-cain13/R.swift#222]
I am using R.swift from day 1 in my project.

## Recently when I added [ECSlidingViewController](https://github.com/ECSlidingViewController/ECSlidingViewController), the build started failing.

-----
This was the one of the method generated by R.swift
`func mainNav(_: Void) -> ECSlidingViewController? {  
        return UIStoryboard(resource: self).instantiateViewController(mainNav)
 }
`

The error given by this method is 
> Use of undeclared type 'ECSlidingViewController'

-----

I created a similar method in one of my ViewController subclass
`func mainNav(_: Void) -> ECSlidingViewController? {
        return nil
    }
`
and it worked fine.

----
Why R.swift is not able to detect the Framework, although it is visible in every other file?
Here is my `Build Phase`
![Imgur](http://i.imgur.com/hwgIed4.png)
----
I am using Xcode 7.3.1 and Swift 2.2

**Comment by mac-cain13** [comment]
If you normally need to write an `import` statement in the file then you should [explicitly state the module in Interface Builder](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Images/ExplicitCustomModule.png). Since the library you link is ObjC you should also make sure you `#import` the correct ObjC file in your product header file.

If it's working everywhere else you should make sure the generated file is linked to the correct target. If all that seems to be correct I'm not sure what the problem is, the generated file is just another Swift file nothing fancy about it other then that it is produced by a program instead of a programmer.

**Comment by mac-cain13** [comment]
I'll assume this was an import issue and explicitly stating the module did fix it. If it's still an issue feel free to comment on this issue again.

**Comment by keduardo2117** [comment]
Still is not working, at least in Xcode 8.3.3 with Swift 3.0

I explicitly declared the module in the Interface Builder, and now the R.generated.swift imports ECSlidingViewController but the method it generates is the next one

`
    func mainNavi(_: Void = ()) -> ECSlidingViewController.ECSlidingViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: mainNavi)
    }
`

And the error thrown is ECSlidingViewController is not a member of ECSlidingViewController

**Comment by keduardo2117** [comment]
A Workaround is to subclass ECSlidingViewController like this

`

    import ECSlidingViewController

    class WorAround: ECSlidingViewController {}

`

And set the child class in your storyboard

**Comment by mac-cain13** [comment]
Good workaround, note that this error you see is a bug in the Swift compiler: https://bugs.swift.org/browse/SR-898 When a type has the same name as the module it is in you get an error when you reference it.
