### ISSUE TITLE
build failed with exit code 132

### ISSUE THREAD

**Issue by romk1n** [mac-cain13/R.swift#227]
```Script-55033B1C1C34428300E00B74.sh: line 2: 40025 Illegal instruction: 4  "Pods/R.swift/rswift" "$SRCROOT"
Command /bin/sh failed with exit code 132```

started to get his issue, any idea ?

**Comment by tomlokhorst** [comment]
I just ran into this issue as well.

This happens when the `project.pbxproj` file is corrupted.
In my case I a reference to a file that wasn't defined. This happened because I had manually merged the file incorrectly.

I figured out what te problem was because cocoapods showed a warning:

```[!] `<PBXGroup path=`Fixtures` UUID=`D50D60F11CEB67C0006D26F7`>` attempted to initialize an object with an unknown UUID. `D5F5F83E1D083CF30070AC8B` for attribute: `children`. This can be the result of a merge and  the unknown UUID is being discarded.```

R.swift should have a better fallback for dealing with corrupted project files. Similar to cocoapods.

**Comment by romk1n** [comment]
That's right it was an issue with project file but because r.swift executes first it wasn't showing the correct problemm

**Comment by Noodlekim** [comment]
I remove this issue. 
I have just released R.generated.swift file from navigator. And then refer R.generated.swift again.

**Comment by rafaelnobrepd** [comment]
I had this today, and one of my `Copy bundle resources` build phase had a bogus, duplicated xib file from a bad merge.

**Comment by Shunzi007** [comment]
I had this issue too.

**Comment by tomlokhorst** [comment]
I'm working on a new version of XcodeEdit (https://github.com/tomlokhorst/XcodeEdit/pull/22) that should prevent crashes in R.swift.

If there's a bad merge in the project file, R.swift will print a warning describing the error in the project file, instead of crashing.
