### ISSUE TITLE
Could not infer type for "XXXController"

### ISSUE THREAD

**Issue by Onetaway** [mac-cain13/R.swift#242]
I follow the install step. Drag the R.generate.swift file to project.  Them compiled the project.
It takes the error as title.  `Could not infer type for XXXController` . This controller is in Main.storyboard. Can some solve the problem?  Thank. :)

The snapshot is: 

<img width="1273" alt="r generated swift xcode today at 16 52 05" src="https://cloud.githubusercontent.com/assets/3251826/17206728/c1021098-54e3-11e6-8469-a51050303c66.png">

**Comment by tomlokhorst** [comment]
It seems like you've configured a custom class titled `personCenterMoreSettingsTableViewController` in the storyboard:

![screen shot 2016-07-28 at 11 02 02](https://cloud.githubusercontent.com/assets/75655/17207025/d8ae2bb8-54b2-11e6-89be-d28fe28f17e7.png)

However that class doesn't exist, as the second error message shows.
Could it be that this is a typo in the storyboard? Since classes usually begin with a uppercase character.

**Comment by Onetaway** [comment]
OK  I will check it.

**Comment by Onetaway** [comment]
Yep.problem solved.  `personCenterMoreSettingsTableViewController ` class is lowercase character, and in InterfaceBuilder. type in `personCenterMoreSettingsTableViewController `, but the IB automatically change it into `PersonCenterMoreSettingsTableViewController` uppercase. So the project still work before I envoled in R.swift. I think it's a IB's bug.
