### ISSUE TITLE
Generate Swift 3 code and support Xcode 8

### ISSUE THREAD

**Issue by techmehra** [mac-cain13/R.swift#246]

**Comment by tomlokhorst** [comment]
R.swift maintenance is on a bit of a summer break at the moment. So we're not very quick with reviewing and responding to issues and pull requests.

Rest assured: We do intend to have a stable Swift 3 version of R.swift before the final release of Xcode 8 this september.

**Comment by tomlokhorst** [comment]
Note to self: It's more important to make sure the code generator outputs Swift 3 code and can handle Xcode 8 file formats.
It is not actually that important if the `rswift` executable itself is still written in Swift 2.3.

**Comment by techmehra** [comment]
Thanks, But can you make a development branch for swift 3.0 so that we can also test the library

**Comment by tomlokhorst** [comment]
Sorry, I should have made that clear: I meant the _executable_ can stick to Swift 2.3.

The R.swift.Library is a separate project that must be updated to Swift 3, since that's something you reference from your app.

There's currently a `swift3` branch for the library project, although that's a work in progress, and some things may still change before release: https://github.com/mac-cain13/R.swift.Library/pull/17

**Comment by mac-cain13** [comment]
TODO: 
- [ ] Add `@available` annotations for new methods in the library

**Comment by mac-cain13** [comment]
An Swift 3 beta version is now available as a beta release! It's not yet available on Cocapods since the pod tools are broken in combination with Xcode 8 atm: https://github.com/CocoaPods/Xcodeproj/pull/404

**Comment by rbresjer** [comment]
Hi @mac-cain13, do the Cocoapods tools work already with Xcode8, now it's released as GM?

**Comment by mac-cain13** [comment]
I'm going to retry today! Hope everything does work now. :)

**Comment by samuel-mellert** [comment]
Good luck! 👍

**Comment by bre7** [comment]
I don't think it does (at least with 1.1.0.rc.1)

**Comment by tomlokhorst** [comment]
For Swift 3, we should also update [this list](https://github.com/mac-cain13/R.swift/blob/master/R.swift/Util/SwiftIdentifier.swift#L143) of Swift keywords.

I'm unsure of how up-to-date [Apple's documentation](https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/LexicalStructure.html#//apple_ref/doc/uid/TP40014097-CH30-ID413) is, since for example `fileprivate` isn't listed.

**Comment by mac-cain13** [comment]
Okay, the release is there 3.0.0.beta.1 is out, that is Swift 3 compatible. I will shortly also release a stable version of R.swift.

**Comment by mac-cain13** [comment]
R.swift 3.0.0 stable is released, this version is Swift 3 and Xcode 8 compatible! Have fun and please create a bug report if you experience any issues.
