### ISSUE TITLE
Errors while building with R.swift

### ISSUE THREAD

**Issue by Otisle** [mac-cain13/R.swift#259]
Everytime I build(after clean the project) the project, and the error always show up but it still able to run!

The message is :
egrep: $PODS_ROOT/R.swift: Is a directory
Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

**Comment by tomlokhorst** [comment]
You might still be able to build because you've a previously generated `R.generated.swift` file that is not being updated.

What script do you have in Build Phases?
It should be something like this:

![screen shot 2016-09-13 at 10 41 23](https://cloud.githubusercontent.com/assets/75655/18467101/e14bd746-799e-11e6-8477-e05f73d11284.png)

Also double check the [installation instructions](https://github.com/mac-cain13/R.swift#cocoapods-recommended) to see if there's something you've missed.

**Comment by Otisle** [comment]
It's the same to yours!
[
![image](https://cloud.githubusercontent.com/assets/12266993/18467358/46c61496-79d2-11e6-981a-b59e1eb782a5.png)
](url)

**Comment by mac-cain13** [comment]
Could you please try to put the R.swift script and the TODO/FIXME script in seperate steps? That would make it more clear where the error is coming from.

Your error message mentions `egrep` which is in the `find` commando. Also `rswift` should always exit with a non-zero exit code if something goes wrong. That indicates to me that the `find`/`egrep` command is giving errors and not R.swift. Splitting up the scripts would make this more clear.

**Comment by mac-cain13** [comment]
I'll close this, feel free to still comment if this isn't the solution!

**Comment by Otisle** [comment]
I've removed the TODO/FIXME script and reinstall R.swift !
It works! everything is great!
Thanks a lot!

**Comment by gemgemo** [comment]
TAGS="warning:"
ERRORTAG="danger:"
find "${SRCROOT}/{TARGET_NAME}" \( -name "*.h" -or -name "*.m" -or -name "*.swift" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$|($ERRORTAG).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/" | perl -p -e "s/($ERRORTAG)/ error: \$1/"

-working without errors
