### ISSUE TITLE
Extending R.swift to custom types

### ISSUE THREAD

**Issue by Bartzy** [mac-cain13/R.swift#263]
I'm trying to understand if it's possible to extend R.swift (for my own use) to support a different kind of resource.

I'm looking to Mirror types (using the Mirror reflection API), and generate an enum of property names to their strings, only for types that adopt some protocol, for example (doing this for all types in an app would be insane).

For example, for this struct:
```swift
struct Person: CustomRswiftReflectable {
    let name: String
    var age: Int
    var isParent: Bool
```

The generated enum would be something like:
```swift
enum PersonProperties: String {
    case name = "name"
    case age = "age"
    case isParent = "isParent"
}
```

Thanks!

**Comment by mac-cain13** [comment]
Theoretically this would be possible, but it's not trivial and I don't think R.swift is the right tool for this. This because R.swift has no knowledge of the source code in your project. We operate before the code goes to the compiler and don't do anything with the swift code ourselves.

Projects like [Swift JsonGen](https://github.com/tomlokhorst/swift-json-gen) and [SourceKitten](https://github.com/jpsim/SourceKitten) do operate on Swift code and are in my opinion a better starting point for a tool like you are describing.

**Comment by Bartzy** [comment]
Thanks!

What happens before the first build, with R.swift? Auto-completion is not working I guess, so when you add a resource, you need to build, then the R.generated.swift file is created and only then you can use it freely in code?

**Comment by mac-cain13** [comment]
Correct. Also when adding a new resource you need to run R.swift before the resource is autocompleted.

**Comment by Bartzy** [comment]
Can you run R.swift without building the project?

**Comment by mac-cain13** [comment]
Yeah that's absolutely possible, you need to provide the input flags that Xcode normally passes to R.swift. Then it will just run as normal.

Just call `rswift` on the commandline to see the input flags you can provide.

**Comment by mac-cain13** [comment]
Yeah that's absolutely possible, you need to provide the input flags that Xcode normally passes to R.swift. Then it will just run as normal.

Just call `rswift` on the commandline to see the input flags you can provide.
