### ISSUE TITLE
Nest class with @objc renaming

### ISSUE THREAD

**Issue by RoCry** [mac-cain13/R.swift#265]
```swift
enum A {
    @objc(NestB) class B: UIViewController {

    }
}
```
I can't use A.B in storyboard, so I use NestB instead.

And R.swift will get the Objc name in swift, which is wrong.

Is there a way to fix it?
Or, can I ignore the .storyboard(one or all) in R.swift so I could handle this manually?

**Comment by mac-cain13** [comment]
Interesting, I wasn't aware this construction is possible!

R.swift has no knowledge of your code at this moment, so it is not possible for R.swift to detect that you don't mean to reference `NestB`, but `A.B` in this case. The only workaround, other than avoiding specific ObjC names, I can think of is running a search an replace in the R.swift build step.

Personally I see a lot of developers that just put the class at the top level instead of nesting it.

**Comment by RoCry** [comment]
@mac-cain13 Is it possible to offer a option to use parts of R.swift.

Like `"$SRCROOT/rswift" "$SRCROOT/Assets" --skip storyboard`

**Comment by mac-cain13** [comment]
In issue #250 there is a discussion about disabling features. So it's not there, but we are thinking about it.

**Comment by mac-cain13** [comment]
I gave this a bit of thought:

- In my opinion this is an edge case not many user will encounter.
- It is quite hard to resolve the correct class to use, since we can't detect this alias. Managing alias lists by hand is not something I think would be a nice solution.
- We could offer a `--skip-file path/to/file` option that makes sure that file is completely ignored by R.swift. This would offer a workaround for people running into this issue.

Unless there are a lot of people running I think that would be an okay solution, it at least gives the ability to keep the code "compilable".

**Comment by RoCry** [comment]
The `--skip-file` solution seems good for most of the cases

**Comment by mac-cain13** [comment]
I'll close this one in favor of #276. I think that will resolve this one as well once implemented.
