### ISSUE TITLE
IBOutlets 

### ISSUE THREAD

**Issue by vandilsonlima** [mac-cain13/R.swift#284]
Just a crazy idea, but would it be possible to R.swift create IBOutlets? I mean when you add a label in the storyboard it creates a IBOutlet in the view controller. This remove the need to drag to the view controller always you need to create a IBOutlet

**Comment by mac-cain13** [comment]
Thanks for submitting your idea and using R.swift! 

I like the idea, but it will be hard to create the outlet in the code since R.swift has zero knowledge about your code. We don't read/interpet the code files. So we don't know where to put the outlet.

Getting the knowledge about the code in your project is a huge task and beyond the scope of R.swift. So I would love this to be automatic, but I'm afraid R.swift will never help you solve this problem.

Thanks again for creating a feature request for this!
