### ISSUE TITLE
R.image.<name> returns nil on iPhone 7(7+) for some images

### ISSUE THREAD

**Issue by ksloginov** [mac-cain13/R.swift#303]
I've noticed, that on iPhone 7 (and 7+):
`UIImage(named: R.image.filter_inactive.name)` - works (returns `UIImage`)
`R.image.filter_inactive()` - doesn't work (returns `nil`)

Particular image which is failing (images below are **white**):
![filter_inactive@2x](https://cloud.githubusercontent.com/assets/1670172/23611833/33c54bca-0279-11e7-8f03-07901e0bcd4f.png)
![filter_inactive](https://cloud.githubusercontent.com/assets/1670172/23611865/49b02eb4-0279-11e7-880e-a7af03059008.png)

I'm using cocoapods:
   Using R.swift (3.2.0)
   Using R.swift.Library (3.0.2)

On all other devices (iPhone 6s, iPads, iPhone SE, etc. ) it works just fine! Reproducible both on simulator and real device.

It happens to very few of images and I don't see any obvious pattern for it to happen :-( 

```
public convenience init?(resource: ImageResourceType, compatibleWith traitCollection: UITraitCollection? = nil) {
    self.init(named: resource.name, in: resource.bundle, compatibleWith: traitCollection)
}
```
is being called, bundle is equal to `Bundle.main`, name is correct, traitCollection is `nil` -- but it still returns `nil` in result. I.e. it looks like that images are just not in bundle, for some reason. (Again, it happens to **very** few)

Has anyone else encountered it?

**Comment by ksloginov** [comment]
Continue investigating:

`UIImage.init(named: "filter_inactive", in: Bundle.main, compatibleWith: nil)` - doesn’t work;
`UIImage.init(named: "filter_inactive")` - works;
`UIImage.init(named: <different image name>, in: Bundle.main, compatibleWith: nil)` - also works;

Targets for `Assets.xcassets` and `R.generated.swift` are the same..

**Comment by tomlokhorst** [comment]
Since loading the image also doesn't work when using the string version instead of R.swift, we at least know its not an R.swift issue.

Have you (accidentally) set some attributes in the Attribute Inspector for this particular image?
For example, the image could be restricted to only show up on an iPad.

<img width="261" alt="screen shot 2017-03-07 at 19 36 02" src="https://cloud.githubusercontent.com/assets/75655/23671970/6eed2778-036d-11e7-8a4a-477989b2083a.png">

A quick way to clean everything up is to remove the image from the asset catalog, and add it again. Also, try removing the app from the phone, and deploy that again. Sometimes old resources are cached when deploying a new version of an app.

**Comment by tomlokhorst** [comment]
I'm closing this issue for now, since it doesn't appear to be R.swift related.

@ksloginov If you have any relevant updates, do let us know!
