### ISSUE TITLE
Add option to not generate lowercase identifiers

### ISSUE THREAD

**Issue by olaf-a** [mac-cain13/R.swift#310]
Our string keys are written in all caps, the generated identifiers look weird. I see that the SwiftIdentifier class has a default parameter to skip lowercasing (lowercaseStartingCharacters). Would be nice to configure this from the commandline.

**Comment by mac-cain13** [comment]
Could you give an example of what happens now and what you would like to happen? All uppercase doesn't really feel right for the name of a property/struct.

Note that I've already made some casing changes that are not enabled by default, could you add the `--edge` flag and see if that suits you better?

**Comment by olaf-a** [comment]
Our string keys are like: "MENU_TITLE". This becomes R.strings.mENU_TITLE. I would like to keep the casing, so R.strings.MENU_TITLE.

**Comment by mac-cain13** [comment]
Giving this a little thought I think adding a flag is not the way to go, R.swift should generate a sane default. Adding flag for these kind of things could easily end up in unmaintainable code and confusing combination of flags.

Since we are already changing the lowercasing behaviour I think that we could put in an exception there for all uppercase strings. If everything is uppercase we could choose to not lowercase anything. We should doublecheck that this doesn't make the compiler complain about uppercase names for properties or something like that.

**Comment by brockboland** [comment]
Another example: we have features identified by acronyms, and prefix related classes and resources thusly. A storyboard might be named something like PHTModules for the primary home tab (PHT). The value in the generated struct in that case would be `R.storyboard.pHTModules`, which is kind of funky.

**Comment by mac-cain13** [comment]
If you add the `--edge` flag to your call to R.swift you get the new naming convention, that will convert `PHTModules` to `R.storyboard.phtModules`. I think in most cases this will makes the names already look nicer.
