### ISSUE TITLE
Compile Error in R.generated.swift when using a 3rd party libraries view controller

### ISSUE THREAD

**Issue by btelintelo** [mac-cain13/R.swift#316]
I'm trying to use this library, whose module name is Player and whose main uiviewcontroller's name is also Player.  https://github.com/piemonte/Player

I get a compile error when using an embed segue:
static func embedSegue(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, MyViewController, Player.Player>

Error: Player is not a member of type Player

**Comment by mac-cain13** [comment]
This is a known issue in the Swift compiler: https://bugs.swift.org/browse/SR-898 Other R.swift users also have hit this problem.

Best is to not use the your module name as a type name in that module if you create a library, but since that is not always possible this workaround might help you: https://github.com/mac-cain13/R.swift/issues/277#issuecomment-266575695

I'll close this issue, but please comment/reopen if it doesn't solve your problem.
