### ISSUE TITLE
New resources wont appear after project modification with synx.

### ISSUE THREAD

**Issue by obozhdi** [mac-cain13/R.swift#358]
Hi guys,

R.swift utility is awesome and I use it every day. 
now i am facing a problem which adds a lot of pain, the problem is R and synx compatibility.
synx is designed to keep the folders and files ordered, so usually it moves Assets folder. after such move R stops adding new image assets (but still works with localized strings assets), meanwhile UIImage(named: "") still works fine. 

i tried moving Assets folder back and also reinstalled R.swift several times. i didnt help me solve it.

could u please advise any approach to fix this problem?

thanx in advance

https://github.com/venmo/synx - synx tool

**Comment by mac-cain13** [comment]
I've used synx a few times and in my case it sometimes happens that it moves the `R.generated.swift` to another place on disk. This is a problem because R.swift will generate the file on the original location, while Xcode will look at an older version of the file that is in the location where it is placed by synx.

Could you check if `R.generated.swift` is still in the same place after running synx?

**Comment by obozhdi** [comment]
I've checked it. It has the same location but doesn't seem to update during builds. After i deleted and recreated it, the bug disappeared. Seems to me it was some XCode bug or smth. Thanx for ur attention.
