### ISSUE TITLE
Change distribution method to script based instead of binary

### ISSUE THREAD

**Issue by ntnmrndn** [mac-cain13/R.swift#36]
Hi,
I had an issue migrating our app to swift 2.0:
See: 
https://github.com/ntnmrndn/R.swift/commit/a1d58b9825c2395dafea3cde7e175ce8c0f3ce74

By forking and editing the source code, I noticed that the script is not being compiled from source but rather distributed as a binary.
While I'm convinced you are honest and while I could probably verify that the binary distributed is the same as the one I would be able to compile myself, I strongly believe it would be better for the user to compile directly the source on his computer, and launch the script using swift command line tools.

**Comment by mac-cain13** [comment]
Hi @ntnmrndn!

Thanks for opening this issue, I'll look into Swift 2 support soon! Helpful to know you managed to work with it making only this change.

On the distribution part; Good point, glad you pointed this out. I'll take it into consideration. Of course your welcome to compile your own binary, but I see how running it as a script would give you more confidence.

I'll split these issues up to make sure both of them are given some thought! Thanks again.

**Comment by mac-cain13** [comment]
I think this should indeed be fixed, users should be able to just run a script that they can check themselves. This will be more transparent and is less scary. :)

**Comment by mac-cain13** [comment]
I think distributing as Swift code would be great, the options I've been looking into all are either to complex by putting a whole Xcode project into your own project or need to merge all Swift code into one file. Also compiling R.swift is not fast enough to do it every build.

So I'll close this issue for now, since I don't see any realistic options in making this happen. If anybody has an idea of how to make this work, I'd love to hear about it. Especially a proof of concept would be awesome!
