### ISSUE TITLE
failed with exit code 1

### ISSUE THREAD

**Issue by adsl99801** [mac-cain13/R.swift#360]
Command /bin/sh failed with exit code 1

Unknown Arguments: /Users/keith/iosProject/TicGame

Arguments:

    outputDir - Output directory for the 'R.generated.swift' file.

this is my screenShot
https://imgur.com/a/eNO4T

**Comment by raymondCaptain** [comment]
I have the same problem when using Xcode 9 and swift 4.
I change R.swift verson to '3.3.0', still have this problem.

**Comment by tomlokhorst** [comment]
The Run Script for R.swift 3.3.0 should not have the `generate` parameter, it should be this:

    "$PODS_ROOT/R.swift/rswift" "$SRCROOT"

The `generate` parameter _is_ needed for R.swift 4.0, but that version hasn't been released yet. It is currently only an alpha release. However, we have already merged the code for R.swift 4 to the master branch. So that's why you're currently seeing documentation for R.swift 4, while CocoaPods still resolves to R.swift 3.3.0.

Sorry about that, that's a bit unclear, I'll update the documentation.
