### ISSUE TITLE
On Delete .swift file issue

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [mac-cain13/R.swift#366]
when i delete the file .swift of an controller or xib it give in error in R.swift file although after deleting the code in R.swift it recreate that file after running script because it exist in the class of viewController and xib in storyboard i think this would be changed.
![screen shot 2017-11-08 at 11 41 56 am](https://user-images.githubusercontent.com/6416095/32534285-ea02a7ac-c47a-11e7-948c-e4d77e9bfb4c.png)

**Comment by SURYAKANTSHARMA** [comment]
@mac-cain13  Kindly check this.

**Comment by tomlokhorst** [comment]
One of your storyboards or xibs probably has a Custom Class set to "ViewController".
If your change or remove this custom class, the compile error should go away.

**Comment by SURYAKANTSHARMA** [comment]
yes @tomlokhorst  you are right but it is look like the bug that if the class don't point to any existing class there is no pointing to create blind custom initializer for that class by R.swift .

**Comment by mac-cain13** [comment]
Not sure if I totally understand your issue, but if you reference a class from a xib or storyboard that doesn’t exist you have invalid code that will crash at runtime. This is what R.swift tries to protect you from, so the only fix then is to only use existing classes from your xib. 

If this is not the problem you encounter could you please explain it with some code examples and/or screenshots?

**Comment by SURYAKANTSHARMA** [comment]
thanks for replying  @mac-cain13 . Yes it will protect me at runtime only if i am using it for now but let say xib or controller is retain by some other developer for future use just remain custom Class to some "DeletedViewController" it is little bit annoying when every time of compilation it recreate the initializer even if it is not to be used yet.  I know it require to delete that custom class from storyboard view controller or xib but think it would be better if it check existence of class before creating initializer.

**Comment by tomlokhorst** [comment]
The existing behaviour of R.swift is as it was intended.

The goal of R.swift is to help developers with static typing of what would otherwise be runtime errors or unexpected behaviour.
In this case, if I make a typo where I write `MyCustomCntroller` instead of `MyCustomController` in my storyboard, I'll get a compile time error, instead of a runtime error. 

And yes, in the case of deleting a custom class `DeletedViewController` that does mean you need to remove the runtime references to it. This is similar to other static references to that class in Swift code.

**Comment by SURYAKANTSHARMA** [comment]
Agreed, thanks @tomlokhorst
