### ISSUE TITLE
Change R.nib.customView() to return UIView

### ISSUE THREAD

**Issue by regant** [mac-cain13/R.swift#380]
Hi!
We use a lot of xibs that contain only one view (not cell) without owners. What do you think about adding an improvement associated with the creation of such views?
e.g. `R.view.customView()` instead of using `R.nib.customView.firstView(owner: nil)`.

**Comment by tomlokhorst** [comment]
Good idea!

I looked at a couple of large codebases using R.swift, none of them use `R.view.customView()` anywhere. It's mostly `super.init(nibName: R.view.customView.name, bundle: R.view.customView.bundle)` in custom view controllers and a couple of `R.nib.customView.firstView(owner: self)`. Most of our custom views do have owners, but that could be an optional argument to the `R.view.customView()` function.

If we want to change this though, it would have to be in the next major version R.swift, since it is a source breaking change.

**Comment by regant** [comment]
So, I didn't suggest to break current sources. I meant to add a new struct `view` to `R` class, which contains methods to create views from xibs. But changing return value of `R.nib.customView()` also resolves this problem.

**Comment by tomlokhorst** [comment]
Oh right, I didn't read your initial post correctly. I conflated `R.nib` and `R.view` :-)

Introducing `R.view` would indeed work, but it would increase the surface area of the existing `R` struct which I'm a bit hesitant to do (although not completely opposed to).
However since we have this existing `R.nib.customView()` function hanging around which presumably is only very rarely used, I'd rather repurpose that instead.

**Comment by regant** [comment]
Thanks for you reply. `R.nib.customView()` is also a good solution as it will minimize our code too.
It will be brilliant if you implement the enhancement in the next major version.

**Comment by mac-cain13** [comment]
This is now implemented and released in R.swift 5.0.0.alpha.1
