### ISSUE TITLE
Declare Input and Output Files in Run Script Phase

### ISSUE THREAD

**Issue by fabb** [mac-cain13/R.swift#415]
In several WWDC talks, Apple suggests to set the Input and Output files in all run script phases, so the build system can choose to skip a run script phase if nothing changed, improving incremental build time.

How could we improve R.swift‘s behavior here?

Note that I did not yet check if wildcards were allowed in the Input Files field. Or if we could somehow leverage the new File List field.

**Comment by mac-cain13** [comment]
Good suggestion, I was already thinking if we can leverage this. Few things that I noticed/came to mind:

- We can't modify the new file lists (and also the "old" input files) during build as mentioned in [Building Faster in Xcode](https://developer.apple.com/videos/play/wwdc2018/408/)
- I think generating this list with a command you need to run by hand is to cumbersome, we need something automated for R.swift to make it really useful
- We already do not write the file if there are no changes to prevent Xcode from thinking the file is changed/touched, but still the optimisation of not calling R.swift at all if not needed would be great
- **_I'm wondering if we could add the Xcode project file to the list_**, that would be a nice thing to try. If that work I think we can use that to detect new resources and update the list.

See also the discussion the neighbours at SwiftGen have: https://github.com/SwiftGen/SwiftGen/issues/441

**Comment by mac-cain13** [comment]
Researched this a bit and also discussed this also with @tomlokhorst today;

- Input file lists _must exists_ if the file list doesn't exists compilation fails
- Any file can be given, Xcode just looks at the last modified time of the input file
- We would need to generate an input list of:
  * The project file (to detect added resources)
  * All resources found: images, xibs, storyboards, etc (to detect changes to these resources)
  * All the `Contents.json` files inside asset catalogs (to detect additions/deletions to assets, since those are not mentioned in the project file, and also changes to specific assets)

The big question is how to bootstrap this correctly, since integrating R.swift then would also mean you need to generate a file list by hand to make sure the first compilation keeps working.

**Comment by tomlokhorst** [comment]
Since one of the main features of R.swift is to generate typed references to (new) images. It is fundamentaly
