### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by alexpersian** [mac-cain13/R.swift#42]
Do you have any plans as of yet to implement Carthage support for this repo?

Fantastic project by the way!

**Comment by AndrewSB** [comment]
+1

**Comment by mac-cain13** [comment]
@AndrewSB gave Carthage support a shot in PR https://github.com/mac-cain13/R.swift/pull/46. I think he came to the correct conclusion that since R.swift is not a Dynamic Framework, but a extra buildstep you add to a project we can't add Carthage support.

Carthage in the end is "just" an amazing dynamic framework builder where you still have to do the integration yourself. The only thing we "abuse" Cocoapods for is the integration part, since that is exactly the main thing Carthage is not doing (on purpose) this is a no go. 

If I'm seeing this wrong, please let me know!

**Comment by alexpersian** [comment]
Thanks for the response and explanation. The main advantage I personally see with Carthage over CocoaPods is you are not forced into using a workspace with that additional overhead. But I can see your point, especially since this isn't a Dynamic Framework.

Also props to @AndrewSB for building a PR to try and make it possible.

**Comment by mac-cain13** [comment]
Carthage is a awesome tool, totally agree on that! It's just that it's not so suited for R.swift, would absolutely recommend it for including frameworks. :)

**Comment by tomlokhorst** [comment]
Update per R.swift version 1.0:

The generated code references the Rswift library, which is available through Carthage: https://github.com/mac-cain13/R.swift.Library#carthage

**Comment by alexpersian** [comment]
Great news!
