### ISSUE TITLE
R.swift warning (false positive)

### ISSUE THREAD

**Issue by ricardohochman** [mac-cain13/R.swift#425]
Hi. I got a warning in my project using R.swift:
`warning: [R.swift] Destination view controller with id XcG-7G-HZh for segue showTroubleshoot in HomeMenuViewController not found in storyboard HomeMenu. Is this storyboard corrupt?`

I already tried to change the segue to another name, delete and create again the storyboard reference, among other things, but nothing worked.

What's the solution?
Thanks

**Comment by mac-cain13** [comment]
Could be that the segue is in the XML, but not showing up in the UI since the destination view controller is not there. You could check that by opening the storyboard file as a source code file.

If it really is a false positive it would be nice to have a example storyboard with this problem so we can investigate what case we're missing while parsing storyboards.

**Comment by tomlokhorst** [comment]
Closed due to inactivity.
