### ISSUE TITLE
Images not generated and duplicate locales

### ISSUE THREAD

**Issue by taher-mosbah** [mac-cain13/R.swift#433]
I generate R.generated.swift like this (using version 4.0.0)

```desc "Update R.generated.swift"
lane :r_gen do
  root_directory = "#{File.expand_path(File.dirname(__FILE__))}/../"
  sdk_path = sh("xcodebuild -version -sdk iphoneos Path")
  sh("#{root_directory}rswift generate --accessLevel public #{root_directory} -t app_name --bundleIdentifier com.app_name.ios --productModuleName app_name --xcodeproj ../app_name.xcodeproj --buildProductsDir #{root_directory} --developerDir #{root_directory} --sourceRoot #{root_directory} --sdkRoot #{sdk_path}")
end
```
It used to work for version 3.0 just fine but with version 4.0 and maybe adding a new language (de); I'm having this warning for all my images : 
```
warning: [R.swift] Skipping 2 images because symbol 'map_pin' would be generated for all of these images: map_pin, map_pin
```
And no image entry is generated (existing ones deleted).
As for strings I'm seeing this : 
```
warning: [R.swift] Skipping string for key duration (Localizable), format specifiers don't match for all locales: en, fr, de, en, fr, de
```
Notice the duplicate locales.
Am I missing something ?

**Comment by tomlokhorst** [comment]
Unfortunately, R.swift currently [doesn't support](https://github.com/mac-cain13/R.swift/issues/155) localised resources (other than strings). That's why your localised map_pin isn't generated.

As for the second warning; It seems you're `duration` string doesn't use the same format specifiers in the different localisations. Therefor, R.swift can't generate a function, because it doesn't know what parameters to use.

**Comment by taher-mosbah** [comment]
@tomasharkema actually map_pin is NOT a localised image, as for the duration string I fixed it using the same format. thanks for your time.
