### ISSUE TITLE
Output files validation

### ISSUE THREAD

**Issue by Salfetamen** [mac-cain13/R.swift#475]
I was trying to set up R.swift 5.0.0 in my development pod that is placed in `project_root/Development Pods/pod_name` and got an error `[R.swift] Build phase Output Files do not contain '$SRCROOT/../Development Pods/pod_name/pod_name/Classes/R.generated.swift'.`

The problem is in `EnvironmentValidation.swift:45` where path strings are compared. In my case, `outputURL.path =  project_root/Pods/../Development Pods/pod_name/pod_name/Classes/R.generated.swift` and `scriptOutputFile = project_root/Development Pods/pod_name/pod_name/Classes/R.generated.swift` which both represents single path but strings are different

**Comment by RafaelPlantard** [comment]
I'm facing the same issue, are you find a solution for that @Salfetamen ?

**Comment by Salfetamen** [comment]
Yep, PR with fix linked above (#476)

**Comment by tomlokhorst** [comment]
I don't understand the setup how this issue occurs.

Could you provide an example project that demonstrates this issue?

**Comment by Salfetamen** [comment]
[Example.zip](https://github.com/mac-cain13/R.swift/files/2716161/Example.zip)

Just `pod install` and try to build it

**Comment by MuRanJiangXia** [comment]
error: [R.swift] Output path must specify a file, it should not be a directory.
Is this error？How to solve？

**Comment by tomlokhorst** [comment]
@Salfetamen Thanks for the example, it helped a lot!

@MuRanJiangXia Your issue seems unrelated to this issue, please see our migration guide about this error message: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md

I'll close this issue, we can continue further discussion in the PR https://github.com/mac-cain13/R.swift/pull/476
