### ISSUE TITLE
dequeueReusableCell should return non-optional type

### ISSUE THREAD

**Issue by 417-72KI** [mac-cain13/R.swift#499]
# Suggestion
With using `dequeueReusableCell` for Table/Collection View, we have to implement with `guard let` or *force-unwrapping* because `dequeueReusableCell` returns *optional* type.
But if `R.reuseIdentifier.~Cell` is created, It should be guaranteed by **R.swift** to be registered in Table/Collection View.
For the above reason, I suggest that `dequeueReusableCell` should return *non-optional* type.

# Current
## Definition
```swift
public func dequeueReusableCell<Identifier: ReuseIdentifierType>(withIdentifier identifier: Identifier, for indexPath: IndexPath) -> Identifier.ReusableType?
    where Identifier.ReusableType: UITableViewCell
```
### With `guard let` and `fatalError`
```swift
guard let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier.hogeCell, for: indexPath) else {
    fatalError("hogeCell not registered.")
}
cell.hoge = …
return cell
```
### With `guard let` and `assertionFailure`
```swift
guard let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier.hogeCell, for: indexPath) else {
    assertionFailure("hogeCell not registered.")
    return UITableViewCell()
}
cell.hoge = …
return cell
```
### With `force-unwrapping`
```swift
let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier.hogeCell, for: indexPath)!
cell.hoge = …
return cell
```
# Hope
## Definition
```swift
public func dequeueReusableCell<Identifier: ReuseIdentifierType>(withIdentifier identifier: Identifier, for indexPath: IndexPath) -> Identifier.ReusableType
    where Identifier.ReusableType: UITableViewCell
```
## Usage
```swift
let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier.hogeCell, for: indexPath)
cell.hoge = …
return cell
```

**Comment by mbernson** [comment]
It would be great if this is possible in some way!

As you'll know, you have to register the cells in advance with your tableView (`tableView.register(R.nib.myTableViewCell)`) or collectionView, otherwise your app will crash. 

R.swift currently can't guarantee that you've done that in advance, and I don't see a straightforward way to do that without either introspecting your code or generating a UITableViewController subclass. Both of those are probably not the solution we want to build.

In our projects, we just force unwrap because we _want_ the app to crash if we forgot to register a cell: `let cell = tableView.dequeueReusableCell(withIdentifier: R.reuseIdentifier.myTableViewCell, for: indexPath)!`

And with the current implementation at least the developer can choose how they deal with it.

**Comment by 417-72KI** [comment]
@mbernson, thx for reply!

Certainly, and unfortunately, there is no solution to detect if the cell is registered.

However, I think everyone wants the app to crash if the cell is not registered yet.
(In our project, we use `guard let` and `fatalError`)

That's why, I suggested it to place that responsibility on R.swift.

**Comment by mac-cain13** [comment]
When creating R.swift I've chosen to go for a defensive "never crash" approach. You can find the principles the generated code follows here: https://github.com/mac-cain13/R.swift/blob/master/Documentation/Contribute.md#coding-guidelines

Thing is that it is convenient that R.swift force unwraps for you and most of the time that will not cause problems. But there are a lot of users with a lot of edge cases, I do not want R.swift to be the cause of unexpected crashes in apps.

If you want to take the risk of force unwrapping because you know that's okay in your case it's super easy to add the `!` after the call as @mbernson suggests. The other way around (with R.swift doing the unwrap) is way harder to fix if you need consistent `nil` checking to see if the cell is there.

Note that there are also some older issues with about the same discussion:
- https://github.com/mac-cain13/R.swift/issues/160
- https://github.com/mac-cain13/R.swift/issues/109
- https://github.com/mac-cain13/R.swift/issues/61
