### ISSUE TITLE
Add Documentation For Calling `rswift generate` From The Command Line (For CiCd)

### ISSUE THREAD

**Issue by GregHilston** [mac-cain13/R.swift#520]
We're using Circle CI to build, test and deploy our iOS app.

One of the issues we're running into is the `R.generated.swift` doesn't exist on our CICd platform. We're trying to combat this by incorporating a call to `r.swift generate` before our build, test and deploy phases. 

We're running into a few issues with how to exactly call `r.swift generated` on our CiCd platform. The difficulty has been correct passing in all the paths that Xcode has been setting for us via environment variables. 

Does anyone have any examples of using R.swift on a CiCd platform? We're aware we could have our `r.swift.generated` file in our repo but that's a pretty ugly solution and I'd rather not see this generated file in things like pull requests.

Any help is appreciated!

**Comment by mac-cain13** [comment]
Is there a particular reason why you're not running xcodebuild and having R.swift in there as a build step? Most of the time I'm using Bitrise as CI/CD system and during the build it will generate the R.swift file.

Running the generate command by hand is quite a hassle since we depend on quite some Xcode environment variables that are available during build that you'd have to reproduce and are error prone if you set them by hand. So I wouldn't advise to go down that path.

**Comment by GregHilston** [comment]
> Running the generate command by hand is quite a hassle since we depend on quite some Xcode environment variables that are available during build that you'd have to reproduce and are error prone if you set them by hand. So I wouldn't advise to go down that path.

Completely agreed, which is why we ended up just committing the file, as it was very time consuming to try and setup correctly. 

> Is there a particular reason why you're not running xcodebuild and having R.swift in there as a build step? Most of the time I'm using Bitrise as CI/CD system and during the build it will generate the R.swift file.

We use fastlane to perform our building and unit testing. I'm looking into any documentation, rswift's or otherwise, for how to add a build step as I write this. Can you, @mac-cain13 , provide me with an example as to how I can use xcodebuild to generate my R.swift file?

**Comment by mac-cain13** [comment]
This is quite old already, but for future reference:

If you add the R.swift generate step to the Build Phases for your target in Xcode (as per Readme instruction) then `xcodebuild` will respect that and run R.swift automatically during a build.

**Comment by kochavi-daniel** [comment]
@mac-cain13 

We're also running R.swift from the command line on our CI/CD server and because the following command line options were removed we can't run it anymore:

```swift
static let xcodeproj = Option("xcodeproj", default: EnvironmentKeys.xcodeproj, flag: "p", description: "Path to the xcodeproj file.")
static let target = Option("target", default: EnvironmentKeys.target, flag: "t", description: "Target the R-file should be generated for.")
static let bundleIdentifier = Option("bundleIdentifier", default: EnvironmentKeys.bundleIdentifier, description: "Bundle identifier the R-file is be generated for.")
static let productModuleName = Option("productModuleName", default: EnvironmentKeys.productModuleName, description: "Product module name the R-file is generated for.")
static let sdkRoot = Option("sdkRoot", default: EnvironmentKeys.sdkRoot, description: "SDK root folder that Xcode uses during build.")
 ```

**Comment by eran3d** [comment]
I know the thread is closed and that running R.swift from the command line is not the recommended way.

However...
I run several code-generation scripts, and really don't want them run on every build. I have a 'fastlane generate' lane that I run when necessary.
My project is fairly large and I really want to keep build times a low as I can.
I stuck with the 5.0.0.alpha.3 version for a long time, because my script wouldn't run with newer versions.

Now, I did find a workaround, that maybe helps people in a similar situation.
R.swift depends on environment variables that are availabe when run from Xcode.

To list these variabes the following script can be run:
`xcodebuild -project "../{PROJECT}.xcodeproj" -target "{TARGET}" -showBuildSettings`

I save the output of this script to a local file (added to .gitignore)
and use this file to parse the necessary environment variables to be used in my script. 

The full script I use is:
```
parseEnvironmentVariables() {
	export SRCROOT="$(cat buildSettings.txt | grep -m1 "SRCROOT" | sed 's/^.*= //' )"
	export TARGET_NAME="$(cat buildSettings.txt | grep -m1 "TARGET_NAME" | sed 's/^.*= //' )"
	export PROJECT_FILE_PATH="$(cat buildSettings.txt | grep -m1 "PROJECT_FILE_PATH" | sed 's/^.*= //' )"
	export TARGET_NAME="$(cat buildSettings.txt | grep -m1 "TARGET_NAME" | sed 's/^.*= //' )"
	export PRODUCT_BUNDLE_IDENTIFIER="$(cat buildSettings.txt | grep -m1 "PRODUCT_BUNDLE_IDENTIFIER" | sed 's/^.*= //' )"
	export PRODUCT_MODULE_NAME="$(cat buildSettings.txt | grep -m1 "PRODUCT_MODULE_NAME" | sed 's/^.*= //' )"
	export TEMP_DIR="$(cat buildSettings.txt | grep -m1 "TEMP_DIR" | sed 's/^.*= //' )"
	export BUILT_PRODUCTS_DIR="$(cat buildSettings.txt | grep -m1 "BUILT_PRODUCTS_DIR" | sed 's/^.*= //' )"
	export DEVELOPER_DIR="$(cat buildSettings.txt | grep -m1 "DEVELOPER_DIR" | sed 's/^.*= //' )"
	export SOURCE_ROOT="$(cat buildSettings.txt | grep -m1 "SOURCE_ROOT" | sed 's/^.*= //' )"
	export SDKROOT="$(cat buildSettings.txt | grep -m1 "SDKROOT" | sed 's/^.*= //' )"
	export PLATFORM_DIR="$(cat buildSettings.txt | grep -m1 "PLATFORM_DIR" | sed 's/^.*= //' )"
	export SCRIPT_INPUT_FILE_COUNT=1
	export SCRIPT_INPUT_FILE_0="$TEMP_DIR/rswift-lastrun"
	export SCRIPT_OUTPUT_FILE_COUNT=1
	export SCRIPT_OUTPUT_FILE_0="$SRCROOT/{PROJECT}/Source/Generated/R.generated.swift"
}

getBuildSettings() {
	if [ -f "buildSettings.txt" ]; then 
		echo "The file exists"; 
	else
		xcodebuild -project "../{PROJECT}.xcodeproj" -target "{TARGET}" -showBuildSettings >> buildSettings.txt
	fi
}

rswift() {
	"Pods/R.swift/rswift" generate "$SCRIPT_OUTPUT_FILE_0" --generators image,string,storyboard,nib
}

getBuildSettings
parseEnvironmentVariables
rswift
```
