### ISSUE TITLE
generated swift file contains storyboard, segue structs in a project which doesn't have any storyboards

### ISSUE THREAD

**Issue by aslisabanci** [mac-cain13/R.swift#53]
Hi there, 

First of all, thanks for opensourcing this project :)

I just integrated this with Cocoapods and there's something I couldn't understand. My project doesn't contain any storyboards, thus any segues neither; but after compiling the project, my R.generated.swift file has a storyboard struct, a segue struct with some segues that I couldn't understand where they came from. Also, the reuseIdentifier struct has many duplicate "Cell"  reuseIdentifiers which causes the project not to compile. I couldn't understand where those came from either :) cos I don't have any cells in storyboards or nibs. 

I hope I'm just confused and missing something :) because I'd love to use this a lot!

Thanks in advance and cheers!

**Comment by mac-cain13** [comment]
Thanks for giving R.swift a try and reporting your issue here!

R.swift is currently looking at disk what files are there, the second argument in the build step you added (`$SRCROOT`) is the folder R.swift will scan. You probably have some pods with Storyboards or have some storyboards in this folder (or subfolders) that you deleted from your project but are still on disk.

The duplicate identifiers are considered a bug (see #34) and will be fixed. R.swift should throw a warning about them, but still you should then look into it why R.swift finds multiple files.

So:
- Please check if you have CocoaPods containing these unknown resources you see in the generated file and adjust you buildstep according to the _"R.swift also picks up asset files/storyboards from submodules and CocoaPods, can I prevent this?"_ question in the readme.
- Check if you have resources on disk that you don't use in Xcode and remove those

Hope that helps, please let me know how it works out for you!

**Comment by aslisabanci** [comment]
Hi again!

I found out those storyboards under Carthage's Checkout folder. I had already checked all of my Pods on disk but couldn't have thought of Carthage's Checkout folder. This explains everything. 

I went with the option to exclude all the dependency resources, now everything is great. Thanks for your reply and again, cheers for R.swift! :beers:

**Comment by mac-cain13** [comment]
Good to hear! Happy coding. :+1:
