### ISSUE TITLE
How can I use breakpoint or func print in  source code?

### ISSUE THREAD

**Issue by cpo007** [mac-cain13/R.swift#541]
I want to learn the source code, so I download the source code and success build the R.generated.swift, but I can not use func print or breakpoint in RswiftCore or other code when I run the project.
Did I do something wrong?

**Comment by tomlokhorst** [comment]
Hi, it's cool that you want to learn about the source code!

I never interactively debug R.swift, because it basically behaves like a pure function:
Input goes in the one end (and Xcode project) and output comes out the other end (a R.generated.swift file)

You can add print statements, those will show up when running R.swift.
Note that if you're using ResourceApp, it logs all output to `rswift.log`. So either look in that file, or change the build phase in ResourceApp.

**Comment by cpo007** [comment]
Thanks for your answer. I
