### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by larcus94** [mac-cain13/R.swift#55]
I would be a lot more comfortable using this if this had at least a few tests.
Great work though, I absolutely love this :)

**Comment by mac-cain13** [comment]
Thanks for using R.swift and suggesting this improvement. And I have good news for you! R.swift has tests on the [develop branch](https://github.com/mac-cain13/R.swift/tree/develop)! :)

I want to write some more, but the start is there and they will be in the next release. (I'll close this issue since tests are already setup.)

**Comment by larcus94** [comment]
Ahhh, my bad. That makes it a lot easier to contribute. Thanks! :)

**Comment by mac-cain13** [comment]
No problemo! :)
