### ISSUE TITLE
Extend ImageStructGenerator to support renderingMode

### ISSUE THREAD

**Issue by dirtydanee** [mac-cain13/R.swift#551]
First of all, thanks for all the hard work on the project! 🙏 

I have more of a feature request, than an issue.

In my project I am using single scaled images, most of the times recolouring them. Therefore, after accessing it through the `R.image.${ASSET_NAME}` function, I always have to specify the rendering mode for the asset. 
I ran a quick search recently, and I have already a whooping 206 occurrences! 🤯🤷‍♂️

So, my initial idea was to quickly update the `R.swift.Library` dependency, and modify the convenience initialiser to specify a default `renderingMode`. However, since it is a initialiser, and the `withRenderingMode` API is most likely return a copy of the `UIImage`, specifying the it in the initialiser is not possible.

Looking at the source of `R.swift` it seems that it is [hard coded to generate][1] the API that it ends up calling this convenience initialiser from the `image` struct. I could fork the R.swift project and override this to use an other API, something that I specify for my project, most likely a factory method.

However, before doing that I was thinking maybe you have had some ideas already how to deal with these kind of issues. Furthermore, if we could find a generic, sustainable solution, I would be happy to open a PR!

[1]: https://github.com/mac-cain13/R.swift/blob/509ec796c9d057f7db61fe6b8e22281eee4ef148/Sources/RswiftCore/Generators/ImageStructGenerator.swift#L173

**Comment by mac-cain13** [comment]
Thanks for the compliment and for taking the time to submit this feature request! 👍 

What you want is to set the `renderingMode` to `alwaysTemplate` at those 206 places in your codebase. Am I correct that in plain UIKit (w/o R.swift) that would look something like this:

`let templateImage = UIImage(named: "someIcon")?.withRenderingMode(.alwaysTemplate)`

So the R.swift version you currently use is probably something like: 

`let templateImage = R.image.someIcon()?.withRenderingMode(.alwaysTemplate)`

If I understand your first take correctly your would like to be able to set the rendering mode in the initializer, so then the call side would become something like this:

`let templateImage = R.image.someIcon(renderingMode: .alwaysTemplate)`

The implementation internally would still have to call `withRenderingMode()`, since `UIImage` doesn't have an initializer taking the `renderingMode`. Although this is a little shorter to type I'm not sure it's worth deviating from Apples APIs and what the win is you're looking for.

Could you give an example that illustrates the current situation vs the new situation describing what it improves for developers?

**Comment by dirtydanee** [comment]
Thanks for getting back to me, and sorry for the delay! 😅

The idea would be somehow to be able to define a default rendering mode, or any other default setting on the supported types in `R.swift`.

```swift
let templateImage = R.image.someIcon()
```

would give me already the icon with `. alwaysTemplate `.  

Currently, for images, we use this [convenience initialiser][1]. As you have rightly pointed out, adding the rendering mode will require to drop the current approach of using convenience initialiser, and start having more factory like static functions on the types.

It could be the something like the following:
```swift
make(resource: ImageResourceType, compatibleWith traitCollection: UITraitCollection? = nil, renderingMode: UIImageRenderingMode = ${DEFAULT_RENDERING_MODE})
```

The default rendering mode could be defined in `yml` file. This yml file could be also used for adding further default parameters for other types.

Adding such feature would require definitely some changes in both `R.swift` and `R.swift.Library`. Furthermore, it would require the addition of a `yml` configuration file.

The added value could be to define "richer" API-s in the `R.swift` library, and enable developers to extract default functionality away from their source code into a configuration file.

I understand, this could be a large change, and not necessarily improve the current developer experience . What do you think?

[1]: https://github.com/mac-cain13/R.swift.Library/blob/3365947d725398694d6ed49f2e6622f05ca3fc0f/Library/UIKit/UIImage%2BImageResource.swift#L23

**Comment by mac-cain13** [comment]
While I understand why this is useful in your situation, I feel that this change isn't really a good fit for R.swift. One of our strengths is that we stay pretty close to the behavior of the Apple APIs, this makes it easy to understand and use. R.swift also has sane defaults, is opinionated and is low on configuration settings. I feel features like this deviate a bit too much from that.

**Comment by dirtydanee** [comment]
Thanks for the time and the effort to discuss my feature request 🙏👍

I understand that my request would change the fundamentals of the library and the close behaviour to Apple API-s is an important aspect.

**Comment by mac-cain13** [comment]
You're very welcome.

Really appreciate it when someone uses R.swift and takes the time to write up an idea, issue or feature request. 👍
