### ISSUE TITLE
Destination Directory

### ISSUE THREAD

**Issue by larcus94** [mac-cain13/R.swift#57]
Hi there,

I was wondering if it would be possible to add another argument so that one can specify destination folder. I don't want to have the auto generated file in the root of the project folder but rather in a dedicated resources folder.

What do you think? I would implement this myself but I'm honestly a little confused with your project setup.

**Comment by mac-cain13** [comment]
Yeah good point, this should be a nice thing to support! Currently the directory that you pass in as first argument will also be the directory the `R.generated.swift` file will be outputted in. But thats not always what you want of course.

Definitely something R.swift should support, I have to think a bit about how we should do this, because you now can pass in multiple directories that all will be scanned and get their own `R`-file. Maybe that's a feature we should drop in favor of one input and output dir you can specify.

**Comment by larcus94** [comment]
Yeah I already hacked it together myself this way. It's still easy to scan multiple folders since it's just a build phase.

**Comment by mac-cain13** [comment]
This will be in the next release! v0.10.0 :)

**Comment by larcus94** [comment]
Awesome :)
