### ISSUE TITLE
Detect resources based on resource build step

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#58]
Detect resources based on resource build step in the Xcode project file not based on browsing the users folders. This is would be way more reliable and prevent confusion of files that are missing or duplicated etc.

**Comment by mac-cain13** [comment]
Would need something like https://github.com/CocoaPods/Xcodeproj or https://github.com/mjmsmith/pbxplorer to parse the file, but would be nice to have something written in Swift, so we don't have to depend on a Ruby thing.

`plutil` can convert the `pbxproj` to JSON for easier parsing, so maybe we write something ourselfs, Only converting file references to absolute/relative paths seems to be a little more work. So should look into that a little further.

**Comment by mac-cain13** [comment]
Looked a bit further into build info we get as a build step; The target and project file location are passed to the build script, so that is info we can use to parse the project file correctly and get to the correct resources without making the user configure too much.

**Comment by tomlokhorst** [comment]
I agree that it would be nice to have a native Swift library for dealing the Xcode project file instead of depending on an external tool. Of course you don't want to redo a lot of work, just for the sake of rewriting in another language.

But looking at https://github.com/mjmsmith/pbxplorer, the format doesn't seem all that complicated (even though I'm always confused when I have a git conflict on a project.pbxproj file...). So it might be worth it to create a Swift library that only supports the features needed by R.swift.

Could you list the features needed by R.swift from such a library?

**Comment by mac-cain13** [comment]
We would need the following functionality at minimum:

1. Given a `xcodeproj` file and the name of a `PBXNativeTarget`, return a list of all `PBXFileReference`s included in the `PBXResourcesBuildPhase` of that target.
2. Given a list of `PBXFileReference`s, return a list of absolute paths to those files. (Or relative from the `xcodeproj` file)

Point 1 looked quite simple to me, point 2 is a bit less documented by the existing tools, but CocoaPods/Xcodeproj should have this implemented somewhere. Seems you have to resolve the path based on the group the file is in etc.

**Comment by tomlokhorst** [comment]
Using the `plutil` tool to convert the .pbxproj format to JSON, I've written something to find the paths of all files in Resources build phases.

See the example project here: https://github.com/tomlokhorst/Xcode.swift

**Comment by mac-cain13** [comment]
:heart: 

In the middle of moving all my stuff to my new house, but want to get this into R.swift asap! This will be a major improvement. :smile:

**Comment by mac-cain13** [comment]
This is in since the 0.9 release!
