### ISSUE TITLE
Why must setting the outputfile？

### ISSUE THREAD

**Issue by stackJolin** [mac-cain13/R.swift#587]
The shell script has create the file，why create by "outputfile" secondly

**Comment by tomlokhorst** [comment]
Setting the output file is needed when using the new build system so that Xcode knows the file will exist when building the project after a clean checkout.

See also the [migration guide](https://github.com/mac-cain13/R.swift/blob/master/Documentation/Migration.md#upgrading-to-50) and [related issue](https://github.com/mac-cain13/R.swift/issues/456).

If you’re using the legacy build system, setting the output file is not needed.
