### ISSUE TITLE
Force unwrapped UIImages

### ISSUE THREAD

**Issue by larcus94** [mac-cain13/R.swift#61]
I was wondering whether it would be possible to force unwrap the `UIImage`s so that the different struct vars don't return an `Optional`? Might seem scary but it shouldn't be too dangerous if the library is well tested. What do you think?

**Comment by mac-cain13** [comment]
Thanks for taking the time to suggest this!

I've already put some thought into force unwrapping images and I don't think it's a good idea. This is because an image can be in an asset folder, but not be available at runtime for legit reasons.

For example; `UIImage(named name: String, inBundle bundle: NSBundle?, compatibleWithTraitCollection traitCollection: UITraitCollection?)` its return value is described as:
> An image that exactly or best matches the desired traits with the given name, or nil if no suitable image was found.


Also the AppIcon is a special image that will return `nil` when using `UIImage(named name: String)` at runtime. Then there is the case that you do create an image set in the assets folder, but don't put an image in there. There are just to many options where Apple might return a `nil` value at runtime and I believe R.swift should never make your program crash. That would make things worse instead of better.

Last point is that for example the `image` property on `UIImageView` accepts an `UIImage?` so you don't have to unwrap it yourself and can just write `myImageView.image = R.images.myImage`. Unless there are common use cases where optional images give very ugly code I'm basically not prepared to take the risk of a runtime crash. :)

**Comment by larcus94** [comment]
Oh, I haven't thought about that nor did I look into it really. I guess that makes sense :)

**Comment by mac-cain13** [comment]
Had some colleagues also asking for this feature so did have a look into it earlier. :)
