### ISSUE TITLE
Generate Image namespace structs for different asset catalogs and subgroups

### ISSUE THREAD

**Issue by SpacyRicochet** [mac-cain13/R.swift#613]
In the same vein as namespace structs are generated `R.string` with different localizable files, it would be nice if one could generate namespace structs for different asset catalogs or images in subgroups as well.

### Hypothetical folder structure

```
/Resources
  /UserAcquisition.xcassets
    checkmark.imageSet
    /Onboarding
      /heroImage.imageset
  /ProductPromotion.xcassets
    /heroImage.imageset
```

### Currently generated

```
R.image.checkmark
// heroImage is not generated, because the two different definitions conflict.
```

### Proposed generation

```
R.image.userAcquisition.checkmark
R.image.userAcquisition.onboarding.heroImage
R.image.productPromotion.heroImage
```

Possible duplicate: #610

**Comment by mac-cain13** [comment]
If you load `heroImage` using Apples own UIKit APIs what image would be loaded? I think this is ambiguous since Asset Catalogs are compiled and disappear, so `UIImage(named:)` doesn't have a the catalog as some sort of namespace. You also can't tell `UIImage` what catalog to look into for that reason.

What's your use case here for having an image with the same name in a different asset catalog in the same project? And how does that work without R.swift?

**Comment by SpacyRicochet** [comment]
While this seemed like a good idea, I came to the same conclusion that same-named images make this unworkable. Thanks for considering it!

**Comment by SpacyRicochet** [comment]
Huh, I just discovered that R.swift already appears to do this. It still runs into the "Same named images will conflict"-issue, but very nice!
