### ISSUE TITLE
'Swift' was created for incompatible target x86_64-apple-ios13.0

### ISSUE THREAD

**Issue by ilosqut** [mac-cain13/R.swift#661]
I have Xcode Version 11.6 (11E708). Install RSwift from Swift packages. 

**In build phases:**
swift run -c release rswift generate "$SRCROOT/myPath/R.generated.swift"

**Have the following error:**
/<unknown>:1:1: module 'Swift' was created for incompatible target x86_64-apple-ios13.0: /var/folders/n0/qlkfs56x3h53_k0xppkgl0w40000gn/C/org.llvm.clang/ModuleCache/Swift-2ZHYYI25736UA.swiftmodule

**Tried cleanup ModuleCache folder but no success. Please check.**

**Comment by mac-cain13** [comment]
I think the swift tool is confused because it is ran during the Xcode build proces in the context of an iOS app, but R.swift is macOS app.

Currently we don't support something like `swift run -c release rswift` in the build phase. You can build R.swift first and then reference the build in your build phase.
