### ISSUE TITLE
Error using Mint

### ISSUE THREAD

**Issue by asam139** [mac-cain13/R.swift#675]
mint run R.swift
🌱 Cloning R.swift v5.2.2
🌱 Resolving package
🌱 Building package
[1/3] Compiling XcodeEdit AllObjects.swift
[2/3] Compiling Commander ArgumentConvertible.swift
[3/4] Compiling RswiftCore CallInformation.swift
<unknown>:0: error: error opening '/private/var/folders/y2/5mr8h9kn39l7q580hcjcl1yr0000gn/T/mint/github.com_mac-cain13_R.swift/.build/x86_64-apple-macosx/release/RswiftCore.build/ResourceTypes/Image.swift.o' for output: No such file or directory
LLVM ERROR: IO failure on output stream: Bad file descriptor
error: error: accessing build database "/private/var/folders/y2/5mr8h9kn39l7q580hcjcl1yr0000gn/T/mint/github.com_mac-cain13_R.swift/.build/x86_64-apple-macosx/build.db": disk I/O error
🌱 Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.16". Use --verbose to see full output
🌱  Failed to build R.swift v5.2.2 with SPM

**Comment by asam139** [comment]
With the 5.1.0 works

**Comment by tomlokhorst** [comment]
Can you check if your issue is fixed by updating to 5.3.0?

According to [this comment](https://github.com/mac-cain13/R.swift/issues/679#issuecomment-724050179), using the same version for the library and the tool, fixed the issue.

If your issue still persists, please leave a comment in that other issue.
