### ISSUE TITLE
Assets sorting issues, since R.swift 5.3.0

### ISSUE THREAD

**Issue by ppluskota** [mac-cain13/R.swift#678]
In the new version of R.swift - 5.3.0 I've observed issues with asset sorting. Every time once I rebuild a project the R.generated file is being changed a little bit. The sorting of generated images is being randomized in R.generated file. This causing issues once we are working in a larger team because the file for each team member is a little bit different even if the resources are the same. That was working fine in previous versions

**Comment by tomlokhorst** [comment]
Thanks for your comment. 

My first guess would be that this is due to [stdlib now using a random hash value](https://forums.swift.org/t/psa-the-stdlib-now-uses-randomly-seeded-hash-values/10789). But I'm not sure which Swift version this was introduced, or if that's even relevant here.

In any case, R.swift shouldn't rely on default ordering, and we should always generate code in a stable (alphabetical) order. 

I'll see if I can find the time to figure out where in the generator the sorting is missing. If someone figures it out before me, feel free to send a PR!

**Comment by zac** [comment]
@tomlokhorst Just put in a PR for a fix (I believe). A recent change added a custom comparison, but that comparison only compares the left-hand-side to itself due to a typo.

**Comment by tomlokhorst** [comment]
This should now be fixed in release 5.3.1 (Thanks to @zac)
If you have further issues related to this, feel free to comment here.
