### ISSUE TITLE
Move Segue identifiers into ViewController extensions and make them typed

### ISSUE THREAD

**Issue by mac-cain13** [mac-cain13/R.swift#71]
See https://github.com/mac-cain13/R.swift/issues/34#issuecomment-134694637:

> Segues should be changed so they are an extension on the viewcontroller and not global things. This makes duplicates less likely and if in that situation there are duplicates they really are a problem so a warning is appropriate then.
> 
> This also would enable us to make typed segues in the end.

**Comment by tomlokhorst** [comment]
All other strongly typed resources are under the global `R.*`, no?

Would this change this to something along the lines of `myViewController.R.segue.openDetail`?
Or simply introduce an extra level of namespace: `R.segue.MyViewController.openDetail`.

**Comment by mac-cain13** [comment]
Yeah, have to give this some thought about how it exactly should work, but a segue is really something that is linked to the source view controller. But I think something like:

```
class SomeViewController {
  func someMethod() {
    performSegue(Rsegues.toSettingsSegue) { typedDestinationController in
       something()
    }
  }
}```

Would be great, but as I said have to think about it. The exception here is that nearly all resources are "global" and segues aren't.... What would you prefer @tomlokhorst?

**Comment by tomlokhorst** [comment]
Is the only reason for adding segues to ViewControllers so that they can be strongly typed to the destination? It's a good reason to be sure, but otherwise there is no need to, correct?

Note that to do the performSegue with a callback, you need to also have code in the `prepareForSegue` method. I think it would always require work from the user, it can't all be code generated. See [SegueManager](https://github.com/tomlokhorst/SegueManager/).

**Comment by mac-cain13** [comment]
Typed segues are well underway now, let's close this one and move all discussion to https://github.com/mac-cain13/R.swift/pull/80
