### ISSUE TITLE
Manifest parse error(s)

### ISSUE THREAD

**Issue by anthony1810** [mac-cain13/R.swift#729]
Receive this error after updating to xcode 13 and MacOS Montenrey 12.0.1
My app is an iOS app, written in swiftUI and integrate R.swift with SPM

Unable to build up the project because of following error:
manifest parse error(s)
github.com_mac-cain13_R.swift
![Screen Shot 2021-11-09 at 09 48 08](https://user-images.githubusercontent.com/5018816/140853295-7f383153-03c4-4bf0-9d53-2289d1883ac0.png)

**Comment by ast3150** [comment]
I noticed that this problem was caused not because of the Swift package that I had in my project, but because of having the package also installed separately using Mint. Mint decided to fetch version 6.0-alpha which causes this problem. I updated my Mintfile as follows:

`mac-cain13/R.swift@v5.4.0`

and ran `mint bootstrap`. It works again for me now.

**Comment by tomlokhorst** [comment]
Thanks for your comment. I didn't understand the issue, but now I see it's something related to mint.

Do you happen to know what the actual problem is? 
Maybe this issue will resurface again, when I release v6.0.0.

**Comment by ast3150** [comment]
I don‘t know for sure, but since in the screenshot you see it‘s trying to load an x86-64 library, I suspect this is an issue occurring when using the library on Apple Silicon (arm64 architecture). (I‘m running this on M1 Max)

**Comment by tomlokhorst** [comment]
R.swift 6.0.0 was just released. This version ships as a Universal Binary, with support for M1.

Feel free to comment on this issue, if this issue still persists with version 6.
