### ISSUE TITLE
No such module 'UIKit', using latest 7.1.0 on macOS

### ISSUE THREAD

**Issue by krishsatya** [mac-cain13/R.swift#772]
I'm trying to get `R.swift` working on macOS. I saw that as of 7.0.0, macOS is supported (#766). However when R.generated.swift is created, it is trying to import `UIKit`, which obviously doesn't exist on macOS. Is there a configuration I have to set in order to generate a macOS-friendly file?

![Screenshot 2022-11-30 at 6 06 05 PM](https://user-images.githubusercontent.com/1709184/204927084-e57d5298-9a41-4568-97c5-5fbe7a61aac8.png)

**Comment by tomlokhorst** [comment]
Thanks for your report.

This is a bug.
The storyboard parser interprets the Storyboard as a UIKit storyboard, instead of an AppKit storyboard.

If you have a project without storyboards/nibs, the `import UIKit` won't be generated (unless there's some more bugs I'm not familiar with).

With a future update, the storyboard should work on macOS as well.

**Comment by krishsatya** [comment]
Thanks @tomlokhorst, super helpful. I actually had a stale storyboard file in my project that I no longer needed. Getting rid of it resolved this issue, so I appreciate that tip.

**Comment by tomlokhorst** [comment]
This is fixed in 7.2.0
