### ISSUE TITLE
R.generated is building with failed struct

### ISSUE THREAD

**Issue by jamesvanhallen** [mac-cain13/R.swift#784]
please check image:
<img width="1398" alt="Screenshot 2022-12-09 at 11 42 23 AM" src="https://user-images.githubusercontent.com/8998306/206751014-351bb0e3-5444-40b1-85da-91ac2f629ebe.png">

**Comment by tomlokhorst** [comment]
Thanks for the report.

This happens because one or more of your resources use the asset tag "3", for which R.swift can't generate a valid Swift identifier.
If you're not actually using the asset tag, a quick workaround is to remove the tag from your asset catalog.

For a full solution, I will create an update that no longer generates this invalid Swift code.

**Comment by tomlokhorst** [comment]
This is fixed in version 7.2.3
