### ISSUE TITLE
Selector support

### ISSUE THREAD

**Issue by gpongelli** [mac-cain13/R.swift#84]
Hi,
Thanks for this awesome pod, is in your plan to support selectors' name?
Instead of "Selector("performSomething")" is it possible to do R.Selector.performSomething ?

Thanks!

**Comment by mac-cain13** [comment]
Thanks for using R.swift and suggesting this!

I think it's hard to create because there are so much selectors including all of the selectors created by Apple. Also it only works with methods marked as `@objc` or Objective-C classes. I think it will be a thing that we see less and less in Swift.

So besides that it will be extremely hard to implement, I think it's something we nearly won't use in a few years. If you have an idea how to implement this I'd really like to know!

**Comment by gpongelli** [comment]
You're right, it's hard to implement and with swift it will be used less and less, I've no idea on how to implement this in R.swift too.
PerformSelector is useful as much as awful and sincerely I hope it will be deprecated soon.

**Comment by mac-cain13** [comment]
Agreed, have to say I've been thinking about this myself, but couldn't come up with a robust solution for R.swift. So I'm afraid we have to live with the stringly typed implementation here. :(

I'll close this one!
