### ISSUE TITLE
Support same name of cell identifiers in different controllers

### ISSUE THREAD

**Issue by huynhphan89** [mac-cain13/R.swift#85]
It's hard for me to make sure all cell identifies are different in lots of controllers and storyboards.
Would you like to support that?
Thanks.

**Comment by mac-cain13** [comment]
Thanks for using R.swift and telling me about your experience with it!

It would be possible to make something like it, but then you would need something like `R.reuseIdentifier.someStoryboard.textCell` for example. Would that be better for you then making the names unique? Or should I just improve the error message so that it will be easier to find the duplicate identifiers?

Personally I feel that you should make identifiers unique so you never will be confused what you're talking about. But if it is giving people lots of trouble I'd love to look into it and change it!

Let me know what you thing!

**Comment by huynhphan89** [comment]
Now, I use controller name as a prefix to make indentifiers unique.
For projects doesnt start with R.swift, the error message is a good idea. It will help a lots.
Thanks

**Comment by mac-cain13** [comment]
Just implemented the following on the 1.0.0 branch:

- if exactly the same identifier is used twice with exactly the same type; no warning and the identifier will be in the R.reuseIdentifier.* struct 
- if identifier resolves to the same name in the struct but are not exactly the same OR types are not exactly the same; generate warning and skip the conflicting identifiers

I think this will solve most of the cases, it makes copy/paste actions possible etc. I'll close this issue, it will be available in the next 1.0 beta
