### ISSUE TITLE
Xcode build with Enterprise Distribution Certificate fails

### ISSUE THREAD

**Issue by vdm-swm** [mac-cain13/R.swift#898]
Our project uses two developer accounts for distribution:

- Production: Apple Developer Account
- Test/Integration: Enterprise Account (inHouse/adhoc)

While building (via codeMagic) works for our production builds without any issues, 
the test/integration builds will always fail with
`No signing certificate "Mac App Distribution" found: No "Mac App Distribution" signing certificate matching team ID "xxxxx" with a private key was found.`

We are using R.swift with SPM and "Run Build Tool Plug-ins" with "RswiftGenerateInternalResources".
Why is "Mac App Distribution" needed in the first place?

**Comment by mac-cain13** [comment]
R.swift should not influence signing in any way. It seems to me like this is an issue unrelated to R.swift. Can you build the same project without running R.swift? (And checking in the R.generated.swift file for example.)

Will close this issue since I really think this is unrelated, but feel free to comment/open a new one once you see that signing is all ok without R.swift and just adding R.swift breaks things.

**Comment by sudhachandran** [comment]
Hi, 
Even our project is facing this issue, is there any resolution? @vdm-swm how did you solve this issue?
