### ISSUE TITLE
Xcode warning for duplicate UITableViewCellIdentifiers

### ISSUE THREAD

**Issue by kylejm** [mac-cain13/R.swift#99]
I'm getting this warning:

```
Skipping 2 reuseIdentifiers because symbol 'basicCell' would be generated for all of these reuseIdentifiers: BasicCell, BasicCell
```

It's good informed about this by R.swift, but I don't think it should be a warning.

I'm using the same identifier in a two different UITableViewControllers, which I'm sure isn't uncommon, and now there's a warning stuck in my Xcode. Having R.swift create one string for both of these view controller isn't going to cause any problem, or am I missing something?

Thanks for making R.swift! It's awesome!

**Comment by mac-cain13** [comment]
Thanks for using R.swift and taking the time to create an issue here! :)

The "problem" is that you can use one "BasicCell" identifier for your subclass `BasicCellOverview` and then the same identifier for a subclass `BasicCellDetail`. 

If you then use:
`let cell = tableView.dequeueReusableCellWithIdentifier(R.nib.basicCell.reuseIdentifier, forIndexPath: indexPath)`

What type is cell at this moment, `BasicCellOverview` or `BasicCellDetail`? This is why I throw a warning when using the same identifier twice.

A nice improvement would be to check if the same identifier is used with the same cell class. In that case they are exactly the same and I could just ignore

**Comment by kylejm** [comment]
Ahhh I see. Good point!

In this case, it is the exact same cell class. In fact, it's the basic cell you can select in IB (`UITableViewCellStyleDefault`).

Could I put forward a +1 for such a feature? :blush:

**Comment by mac-cain13** [comment]
Your +1 is noted. :)

**Comment by mac-cain13** [comment]
I would change the reuseIdentifier behavior to the same behavior segues will use in PR #80. Here we only flag a segue as conflicting if the types do not match, so:

Having segue `"foo"` of class `MySegue` from `UIViewController` to `MyViewController` twice is okay, but segue `"foo"` of class `UIStoryboardSegue` from `UIViewController` to `MyViewController` would conflict. Since it's type is not the same.

This makes reuse of identifiers possible when their exactly the same. We could also do this for table- and collectionview cells to make reuse of identifiers possible if their of the same class. This ensures type casts will succeed.

It still won't be possible to mark all kind of cells just with a `"foo"` identifier if they are of classes. I also consider this not a really good practice.

**Comment by kylejm** [comment]
@mac-cain13 +1!

**Comment by fpillet** [comment]
+1 too!

I sometimes duplicate whole view controllers with minor changes, use the same base class and keep the same cells. This results in having to use the cell's string identifier in the base class because R won't generate an identifier even when the cells are the exact same type.

**Comment by mac-cain13** [comment]
Let's continue discussing this one in #85
